name: Atualizar Ranking CNB 500 km Automático

on:
  schedule:
    - cron: '59 2 * * *' # Roda todo dia às 23:59h (horário de Brasília)
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar bibliotecas
        run: pip install requests pandas openpyxl

      - name: Executar robô
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: python ranking.py

      - name: Commit e Push dos resultados
      run: |
        git config --global user.name "Robo CNB"
        git config --global user.email "actions@github.com"
        
        # Adiciona o arquivo gerado pelo script
        git add Ranking_CNB_500km_2026.xlsx
        
        # Só faz o commit se houver realmente alguma mudança no arquivo
        git diff --quiet && git diff --staged --quiet || git commit -m "Ranking atualizado"
        
        # PUXA AS NOVIDADES DO SERVIDOR ANTES DE ENVIAR (Resolve o erro)
        git pull origin main --rebase
        
        # Envia de volta para o GitHub
        git push origin main
